### ISSUE TITLE
Review FLIR fullfield extractor and output

### ISSUE THREAD

**Issue by max-zilla** [terraref/reference-data#182] opened 2017-09-07 13:21 UTC
Review issue for the fullfield extractor and output using flir thermal IR inputs.  

Completion criteria:
* [ ] Code review complete (includes extractor, any functions in terrautils, etc)
* [x] Sample data output verified 
* [x] Sample metadata verified
* [ ] Changes for 2017 release implemented
* [ ] Issue(s) for changes postponed until 2018 created 
* [ ] Extractor tagged/versioned
* [ ] Extractor deployed
* [ ] Quality statement complete
* [ ] Final output verified/reviewed

**Comment by max-zilla** [comment] 2017-09-07 13:24
LINKS

**fullfield output dataset example**
https://terraref.ncsa.illinois.edu/clowder/datasets/59b0e2134f0ca12ea0ce678a

an output dataset includes thumbnail- and full-resolution GeoTIFFs. 

Ignore that this linked dataset has thousands of files, this is a glitch in extractor upload code. The top two .tif files are just duplicated endlessly so just look at the first ones listed.

outputs on ROGER are in /ua-mac/Level_1/fullfield.

**Comment by dlebauer** [comment] 2017-09-07 15:28
One of the full field IR stitched images looks like this:

![image](https://user-images.githubusercontent.com/464871/30171265-1a583c9a-93b7-11e7-99fd-03dde4a75fa2.png)

With values ranging from 1221 to 1574. If this is temperature (K), values should mostly be in the range 275-300

**Comment by dlebauer** [comment] 2017-09-07 15:34
A lower priority issue is that these show up blank in the Clowder interface: 

![image](https://user-images.githubusercontent.com/464871/30171618-17116c54-93b8-11e7-8f0d-a5b21f080633.png)

**Comment by ZongyangLi** [comment] 2017-09-07 16:52
@max-zilla @dlebauer 
In the flir extractor code here: https://github.com/terraref/extractors-multispectral/blob/master/flir2tif/Get_FLIR.py#L174
Just make a very simple update that from
`if not calibP.calibrated:` to `if calibP.calibrated:`

And then the extractor will output a degree centigrade in geotiff files. That's a misunderstanding of the parameter in metadata of `"is calibrated"`, if we are looking for an output of Kelvin temperature we should delete the Kelvin parameter `273.15`.

**Comment by ZongyangLi** [comment] 2017-09-07 17:43
@max-zilla 
Please use the updated codes here: https://github.com/terraref/extractors-multispectral/blob/master/flir2tif/Get_FLIR.py

**Comment by dlebauer** [comment] 2017-09-07 22:17
The variable to be inserted into BETYdb is surface_temperature with units of K. See https://terraref.ncsa.illinois.edu/bety/variables/6000000198 or https://terraref.ncsa.illinois.edu/bety/api/beta/variables?key=9999999999999999999999999999999999999999&name=surface_temperature

**Comment by dlebauer** [comment] 2017-09-07 22:40
Questions about the extractor https://github.com/terraref/extractors-multispectral/blob/master/flir2tif/Get_FLIR.py

* [ ] there are many magic numbers that appear without comment, 
    * examples: gmin, gmax, H, T, D, E, HEIGHT_MAGIC_NUMBER 
* [ ] there are many functions that appear to belong in (and / or are redundant with) terrautils 
    * examples: createVrt, createMapTiles, generate_googlemaps, parse_metadata, get_bounding_box, get_bounding_box_with_formula, create_geotiff
    * are these all currently used in the pipeline?
* [ ] [Line 226](https://github.com/terraref/extractors-multispectral/blob/master/flir2tif/Get_FLIR.py#L226 ) says "TODO Something wonky w/ uint8s --> ending up w/ lots of gaps in data (white pixels)". Can this be fixed now? If not, please add to the quality statement and create a new github issue to track this.

**Comment by max-zilla** [comment] 2017-09-08 13:18
@dlebauer 

- merged your branch to output as units K, and updated bety trait name in meantemp extractor correspondingly.
- our extractor calls one method directly, rawData_to_temperature(), which calls:
  - get_calibrate_param(), pulling calibrations from metadata
  - flirRawToTemperature(), containing the following magic numbers/formula:
```
    H2O_K1 = 1.56
    H2O_K2 = 0.0694
    H2O_K3 = -0.000278
    H2O_K4 = 0.000000685
    
    H = 0.1
    T = 22.0
    D = 2.5
    E = 0.98

    K0 = 273.15
    
    im = rawData
        
    AmbTemp = T + K0
    AtmTemp = T + K0
        
    H2OInGperM2 = H*math.exp(H2O_K1 + H2O_K2*T + H2O_K3*math.pow(T, 2) + 
    H2O_K4*math.pow(T, 3))
    a1b1sqH2O = (a1+b1*math.sqrt(H2OInGperM2))
    a2b2sqH2O = (a2+b2*math.sqrt(H2OInGperM2))
    exp1 = math.exp(-math.sqrt(D/2)*a1b1sqH2O)
    exp2 = math.exp(-math.sqrt(D/2)*a2b2sqH2O)
        
    tao = X*exp1 + (1-X)*exp2
        
    obj_rad = im*E*tao
        
    theo_atm_rad = (R*J1/(math.exp(B/AtmTemp)-F)) + J0
    atm_rad = repmat((1-tao)*theo_atm_rad, 640, 480)
        
    theo_amb_refl_rad = (R*J1/(math.exp(B/AmbTemp)-F)) + J0
    amb_refl_rad = repmat((1-E)*tao*theo_amb_refl_rad, 640, 480)
        
    corr_pxl_val = obj_rad + atm_rad + amb_refl_rad
        
    pxl_temp = B/np.log(R/(corr_pxl_val-J0)*J1+F) - K0
```   
- for now, if @ZongyangLi can document this formula that is probably sufficient. we could put a short portion in README saying "the pixel values are converted to K using the following" or something.
- the other functions you mention are not used in our pipeline. our extractor code calls the terrautils versions of those things - those are likely old versions Zongyang used last year during development.
- line 226 is not reached anymore, we call terrautils version of create_geotiff. but because I used portions of this code as a basis, uint8 is still the format used: https://github.com/terraref/terrautils/blob/master/terrautils/formats.py#L75 we can first see if the white pixel issue still exists in our test outputs.

**Comment by max-zilla** [comment] 2017-09-08 13:54
@ZongyangLi OK, i have a flag in terrautils create_geotiff that lets use determine wtherh to use Float32 (FLIR) or Byte (RGB) so I think that comment can be removed.
```
if asfloat:
        output_raster = gdal.GetDriverByName('GTiff').Create(out_path, ncols, nrows, channels, gdal.GDT_Float32)
    else:
        output_raster = gdal.GetDriverByName('GTiff').Create(out_path, ncols, nrows, channels, gdal.GDT_Byte)
```

**Comment by dlebauer** [comment] 2017-09-09 05:23
@ZongyangLi and @max-zilla looking at the image in https://github.com/terraref/reference-data/issues/182#issuecomment-327835162 it appears there are some white pixels, consistent with the error mentioned in line 226. 

@ZongyangLi could you please update the code to remove obsolete lines / functions that have been migrated to terrautils?

**Comment by ZongyangLi** [comment] 2017-09-09 16:07
@dlebauer I think we had updated the codes relate to  the error mentioned in line 226. 

Actually lines from 226 to 237 was commented by line 225 and 238 `'''`, these lines are used to make a rgb full field map letting me have an easy way to review the map during my development. All the geotiff creations are using [line 218](https://github.com/terraref/extractors-multispectral/blob/master/flir2tif/Get_FLIR.py#L218).


@max-zilla shall we set up another short skype chat to discuss how to remove my initial codes on Github? I believe you had merge a lot of codes into terrautils.

**Comment by max-zilla** [comment] 2017-09-11 14:54
a new full field stitch has been created here:
```/sites/ua-mac/Level_1/fullfield/2017-08-01/```
https://terraref.ncsa.illinois.edu/clowder/datasets/59b681aa4f0c0b27bc24843f 

...created using images from 08/01 e.g.:
https://terraref.ncsa.illinois.edu/clowder/datasets/59b2ec6c4f0ca12ea0d7a162

...with corrected temperature conversion.

**Comment by max-zilla** [comment] 2017-09-11 15:00
In this stitch, the western half is consistently cooler than eastern:
<img width="352" alt="screen shot 2017-09-11 at 9 58 21 am" src="https://user-images.githubusercontent.com/14166971/30281408-f1b31930-96d7-11e7-97f2-5f274092c2ef.png">

...but only with a narrow K range (dark min = 305, light max = 315).
Using a broader color range from 60-120F (285-325K) the field is pretty regular with a small number of warmer plant blades:
<img width="349" alt="screen shot 2017-09-11 at 9 58 03 am" src="https://user-images.githubusercontent.com/14166971/30281428-003001ee-96d8-11e7-9cac-873f2eb9d516.png">

**Comment by pless** [comment] 2017-09-12 14:29
Hi everyone,
 Something is clearly wrong with this stitched mosaic.  @ZongyangLi and I are trying to debug the problem.  We are exploring.
(a) is there something in the actual recent sensor data that suggests that one side of the image is consistently cooler than the other, or
(b) is there a bug in how we are converting the raw data to the temperature value that is causing us to have this trend, or
(c) is there a bug in the way that the stitching process proceeds that leads to this false trend.
We hope to have an answer asap.

**Comment by max-zilla** [comment] 2017-09-12 14:40
@pless thanks for the update. let me know if i can answer questions or point to to where code is being used.

**Comment by ZongyangLi** [comment] 2017-09-12 15:12
@max-zilla @dlebauer @pless 

After downloading the flir raw data, I happen to realize that the flir scan is also in a vertical directory, like the one in stereoTop scan. Would it be the reason why western area different from eastern area?

**Comment by dlebauer** [comment] 2017-09-12 16:05
@ZongyangLi the east-west temperature discrepancy occurs within an image, so should be independent of the file organization.

**Comment by dlebauer** [comment] 2017-09-12 16:11
eg https://terraref.ncsa.illinois.edu/clowder/datasets/59b044014f0ca12ea0bab961
![img_3131](https://user-images.githubusercontent.com/464871/30336433-ceec6766-97aa-11e7-976a-b69dadd53192.PNG)

**Comment by max-zilla** [comment] 2017-09-12 16:57
@ZongyangLi we did confirm that the flirIr is a vertical scan on this date, just like stereoTop (only X increases in gantry coordinates). so potentially, could explain why the field gets warmer as we move to the right (day is getting hotter).

doesn't explain why the individual images have that pattern, however.

**Comment by max-zilla** [comment] 2017-09-12 17:22
@ZongyangLi @craig-willis and I spot-checked a few datasets from 2016 with our old extractor and didn't see this pattern, but we did see this pattern starting with the May 2017 datasets.

doesn't answer the question - maybe something changed with sensor over winter, or the updated extractor code from terrautils isn't properly converting temperature (even though I would expect a problem across the entire image and not just in the left side then)

**Comment by ZongyangLi** [comment] 2017-09-12 20:32
@dlebauer Thanks a lot for helping me get the point of the problem.

@max-zilla Thanks for the check, I also downloaded some example data from different days in 2017.

An initial conclusion here: camera in the right-top is impacted by some unknown factor.
Start from 2017-05-03 to 2017-05-13 flir data is unreasonable like this:
![5bfea5ad-cc1f-4f57-bac8-35bc7c2988d1_ir](https://user-images.githubusercontent.com/20230686/30346467-6c76bd1a-97ce-11e7-9c5f-c259b4c8c8b8.png)
after that, from 2017-05-16, pictures are getting back, but in the right-top corner, images are getting blurred.
![77d63fec-c7aa-43a2-95fc-921578739933_ir](https://user-images.githubusercontent.com/20230686/30346525-a7077fa0-97ce-11e7-8714-48b3559d44ed.png)
In 05-25, it seems to me that the left side of image is clearer than the right side.
![802e9e9c-fe3b-4460-a772-4a8022954a8b_ir](https://user-images.githubusercontent.com/20230686/30346611-ed198f56-97ce-11e7-8fbc-83eab144742b.png)
Things are getting worse after that:
![9deca40a-2eb3-46f9-b4fc-63c1af498a0d_ir](https://user-images.githubusercontent.com/20230686/30346632-07b990c2-97cf-11e7-839b-19586628bc45.png)
![f102a924-3ed1-489b-b233-545812cda763_ir](https://user-images.githubusercontent.com/20230686/30346641-1060d3b6-97cf-11e7-81a0-b6f7cab54cfe.png)
![fc4877d7-c69e-4026-8854-2e396b1fc680_ir](https://user-images.githubusercontent.com/20230686/30346655-1a1d3566-97cf-11e7-8ace-cd184fa4c9c6.png)
Finally in July, images becomes to the picture we seen before:
![970172c9-2d32-48f8-a9d5-32dd5b31627c_ir](https://user-images.githubusercontent.com/20230686/30346705-464ea0b6-97cf-11e7-9e34-39c96cf23561.png)
![c5eba851-5f05-4d82-95a0-90f37f94ba97_ir](https://user-images.githubusercontent.com/20230686/30346711-4c24bf70-97cf-11e7-83f6-a15ebc86b933.png)

I was thinking is it possible a camera problem rather than the extractor problem at this point.

**Comment by smarshall-bmr** [comment] 2017-09-13 05:34
This is pretty weird, I'm pulling data to check this. It almost looks like the autofocus is being confused or something got inside the camera housing.

**Comment by max-zilla** [comment] 2017-09-13 13:51
@ZongyangLi nice detective work.

**Comment by smarshall-bmr** [comment] 2017-09-13 23:37
https://drive.google.com/open?id=1MHtNlCjWWaD_mXx1Zw83lXmh5Jh8eZL6Ug
The outside of the FLIR has been cleaned pretty regularly. I'm checking with folks to see if I'm allowed to open the case to check to see if anything has gotten inside.

**Comment by smarshall-bmr** [comment] 2017-09-15 00:05
I tried running a whole bunch of tests today trying to pin down why the FLIR is making such terrible images and finally went with the nuclear option and opened the weatherproof case. Turns out the weatherproof case isn't Arizona-proof!
![img_20170914_163237](https://user-images.githubusercontent.com/19151535/30460901-df1dfee0-996e-11e7-9261-4148c9db3962.jpg)

**Comment by smarshall-bmr** [comment] 2017-09-15 00:47
I looked back through the field book. There were sprinkler irrigations on 5/1 and 5/4. I'm thinking the inside of the case filled with some water causing the completely unreasonable data which I was working on troubleshooting when the FLIR suddenly just started working again. Because it was right at the beginning of the season after a bunch of power cycles I thought it was caused by the FLIR being too hot from one of the cooling circuits being turned off and I didn't look into it further.

Good news/bad news is that the problem should be pretty consistent over the whole season.

**Comment by dlebauer** [comment] 2017-09-15 01:07
We need to mark all FLIR data as having a known error since that date, and exclude it from the pipeline.

**Comment by dlebauer** [comment] 2017-09-15 03:49
PS thanks for tracking this down everyone. Let's discuss next steps with the team Tuesday and Wednesday.

**Comment by NewcombMaria** [comment] 2017-09-15 13:55
@dlebauer and @smarshall-bmr I'm not understanding fully when the problem with FLIR data began.  A full-field stitched Flir image was assembled by @max-zilla and @ZongyangLi using data collected the week of May 22.  My understanding from the glimpses in closed Github issue #327 ('Generate full field flirIR image from week of May 22') was that the images looked great.  We went into the Stomatal Regulation Field Campaign with some confidence that the full-field FlirIR suggested high quality data.  

![image](https://user-images.githubusercontent.com/22008637/30484942-ce4552f4-99e0-11e7-9412-d8a9f01f882d.png)

@smarshall-bmr we were careful during the early season sprinkler runs (which ended May 4) to raise the camera box and keep it North of the sprinklers until either you or I ran it South so it would only intersect briefly with the sprinklers.  The only exception was a glitch in communication the night of April 28 that was documented in Slack.
 (https://terra-ref.slack.com/archives/C2MF45G2D/p1493403571162894)  
The camera box was checked after that night and all looked ok.  

I agree with @dlebauer comment to discuss the topic with the team Tue and Wed.  The thermal Flir data is critical to 2 of 3 field campaigns (stomatal regulation and stress effects on photosynthesis).  I'm hopeful from the data view the week of May 22 that some data may be good quality.

**Comment by dlebauer** [comment] 2017-09-15 14:21
Stuart if you haven't cleaned the camera yet I think a high priority will be to take some ground truth images to see if we can correct this. From Zongyang's images above it does seem the images were inconsistent. In the worst case the water  sloshed around as it evaporated over a the season. Are there any other potential sources of water? The AC perhaps? The sand and salt may be a separate source. Are there other instruments that need to be checked?

**Comment by dlebauer** [comment] 2017-09-15 14:22
Maria- we may be able to get useful data, but not in time for the November release.

**Comment by dlebauer** [comment] 2017-09-15 14:24
Maria in the image you posted in https://github.com/terraref/reference-data/issues/182#issuecomment-329789752 the leaves on the left appear cooler than the rest, which is consistent with what we have observed. The temperature scale may have made this less obvious when (wet?) soil was also in the scene.

**Comment by NewcombMaria** [comment] 2017-09-15 15:59
Thanks David.  Yes good suggestion to do what we can to allow ways to correct for this down the road, like ground-truth images etc.  Also looking into image overlap.

**Comment by smarshall-bmr** [comment] 2017-09-15 18:52
@dlebauer When we go to try and correct this should we take a set of images in standardized conditions, then clean out the camera and take a second set in the same conditions so we can more precisely determine what changed?

@NewcombMaria If memory serves correctly, wasn't there a pretty violent storm around this time? That would seem more likely then the sprinkler scenario.

Right now I'm thinking the cause for the inconsistencies is temperature related given that the housing lens is supposed to be IR transparent but the temperature of the salt on the lens is probably adding to the signal because the camera is focusing through it.

**Comment by dlebauer** [comment] 2017-09-15 21:43
@smarshall-bmr that sounds like a good plan but I'll defer to experts - Robert or folks from lemnatec & FLIR.

**Comment by max-zilla** [comment] 2017-09-19 13:35
https://terraref.ncsa.illinois.edu/clowder/datasets/59ba90ec4f0c0b27bc3cf7db

I generated full-field for FLIR on 05/29 so we have a day that has both FLIR and RGB stitches available.

There are also 05/29 Thermal IR tiles available.
https://terraref.ncsa.illinois.edu/clowder/collection/59c019e34f0c0b27bc3e9db4
e.g.
https://terraref.ncsa.illinois.edu/clowder/datasets/59c06ef24f0c0b27bc498515

**Comment by max-zilla** [comment] 2017-09-21 16:35
Generate a 2016 full field sample as well.

**Comment by dlebauer** [comment] 2017-10-12 16:08
Every through May 1, 2017 is OK; earlier data can be run. 

* Still need review of samples.
* mark data from May 1 2017 as bad. Process through geotiff but no further

**Closed** 2018-06-07 19:00 UTC
Labels: data-review
