### ISSUE TITLE
Test object data availability from acceptance testing

### ISSUE THREAD

**Issue by nshakoor** [terraref/reference-data#131] opened 2017-05-24 18:43 UTC
Is the data available from the imaging of the test objects that were used in the acceptance testing? If so, is this part of the alpha release? If not, can it be made available, along with the test object specifics?

**Comment by dlebauer** [comment] 2017-05-25 15:50
yes, data are available. 

here are sensor datasheets: https://drive.google.com/open?id=0By_PDCcY5g2JS3BWX2MydTJhZDQ

closing as duplicate of #132

**Closed** 2017-05-25 16:18 UTC
